version: '3.8'
services:
  db:
    image: postgres:15
    container_name: car_parts_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: parts_catalog
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

### ДЛЯ АКТИВАЦИИ ПРОПИШИ В ТЕРМИНАЛЕ В ПАПКЕ С ФАЙЛОМ
### ВКЛЮЧИ ДОКЕР
### docker-compose up -d

### Создание таблиц (Активация кода)
#Скопируй файл прямо в контейнер:
#docker cp BD_dead_kolesa_kz.sql car_parts_db:/tmp/setup.sql

#Запусти его выполнение внутри:
#docker exec -it car_parts_db psql -U myuser -d parts_catalog -f /tmp/setup.sql
# ДЛЯ ПРОВЕРКИ ЧТО ВСЁ СОЗДАЛОСЬ УСПЕШНО: docker exec -it car_parts_db psql -U myuser -d parts_catalog -c "\dt"

# Общая команда для входа:
# docker exec -it car_parts_db psql -U myuser -d parts_catalog